### ISSUE TITLE
Add mock testing

### ISSUE THREAD

**Issue by natemcintosh** [CDCgov/cfa_azure#13]
## Goal

Mock the connections to Azure, and check that the functions that make API calls to Azure are called with the correct arguments.

## Context

Mocking provides a handy way to check that our code makes specific calls to Azure, without actually making those calls. This is very handy for adding local tests that can run quickly. Adding in mock calls will give us more confidence that the code making API calls to Azure is correct.

## Required features

- Add mock tests for the `helpers` module as a starting point

## Specifications

- [ ] Ideally one test per helper function.

## Out of scope

- Actually connecting to Azure. I'll make another issue for e2e testing.

## Related documents

- [a useful intro to mocking](https://realpython.com/python-mock-library/)

**Comment by xop5** [comment]
https://github.com/CDCgov/cfa_azure/pull/123
