### ISSUE TITLE
Add CI to run tests

### ISSUE THREAD

**Issue by natemcintosh** [CDCgov/cfa_azure#144]
## Goal
Add Github actions that run all of the tests in this repo.

## Context
I see that there are a number of tests for this package, but that they are not running in CI. Getting the tests running in CI can help drastically reduce breakages in production by catching them before they're merged.

## Requirements
- Ideally use [pytest](https://docs.pytest.org/en/stable/) for running. It is a well established testing framework, that can [discover and run](https://docs.pytest.org/en/stable/explanation/goodpractices.html#test-discovery) `unittest` tests as well.
  - You can add it with `poetry add --group dev pytest` to add it as a development dependency that isn't installed when users install `cfa_azure`.
- Make all the tests run locally
- Set up a github action that installs poetry, uses poetry to install the package, and uses `poetry run pytest .` to run the tests

**Comment by xop5** [comment]
Pull request https://github.com/CDCgov/cfa_azure/pull/164

**Comment by xop5** [comment]
PR closed
