### ISSUE TITLE
Allow option to create a AzureClient from environment variables

### ISSUE THREAD

**Issue by natemcintosh** [CDCgov/cfa_azure#154]
## Goal
Add another option for creating the `AzureClient`, this time from environment variables.

## Context
Currently, the only way to create an `AzureClient` is with a config file. However, in one case, I'm setting up a connection to Azure via environment variables, and I don't have a config file available to the running code. I would like to be able to create an `AzureClient` from the environment variables. 

I imagine a copy of `helpers.check_config_req()` could be made, and then altered to instead check for the existence of environment variables.

**Comment by antoniohndz1** [comment]
Thanks for the suggestion @natemcintosh ! The new update is live which allows the option for creating an `AzureClient` with environment variables. After setting up your environment variables, instead of providing the `config_path` in the `AzureClient()` you can use `AzureClient(use_env_vars=True)`
