### ISSUE TITLE
Issues with `OnTaskFailure` and `ExitOptions`

### ISSUE THREAD

**Issue by kokbent** [CDCgov/cfa_azure#171]
Might need to rollback #169 (turns out the on_task_failure setting is a lot more complicated)

It turns out that you cannot set 
`on_task_failure=OnTaskFailure.no_action` [here](https://github.com/CDCgov/cfa_azure/blob/fc5d1e998489edf9246fac5c73d1f8ff54e89d8c/cfa_azure/helpers.py#L786C25-L786C48) when you do set a bunch of `ExitOptions` [here](https://github.com/CDCgov/cfa_azure/blob/fc5d1e998489edf9246fac5c73d1f8ff54e89d8c/cfa_azure/helpers.py#L877)

The problem here is `terminate_exit_options` there is set to block the dependent task from executing *AND* terminate the job. [L879](https://github.com/CDCgov/cfa_azure/blob/fc5d1e998489edf9246fac5c73d1f8ff54e89d8c/cfa_azure/helpers.py#L879) should change from `job_action=JobAction.terminate` to `job_action=JobAction.none`

cc: @arik-shurygin

**Comment by ryanraaschCDC** [comment]
rolled back the changes from 169 as we fix this

**Comment by xop5** [comment]
https://github.com/CDCgov/cfa_azure/pull/173

**Comment by xop5** [comment]
Arik confirmed the issue was fixed
