### ISSUE TITLE
Allow creation of dependent tasks

### ISSUE THREAD

**Issue by ryanraaschCDC** [CDCgov/cfa_azure#2]
## Context
Azure Batch has the ability to have [tasks depend on other tasks](https://learn.microsoft.com/en-us/azure/batch/batch-task-dependencies). Essentially, it allows you to do map-reduce style jobs, or DAG workflows.

Currently, we do our own version of this by starting jobs in a bash script, waiting for them to finish, and then starting the next.

## General Goals
Would like a to create jobs that depend on each other using this package. A nice side effect of using dependent tasks is that it allows us to make slightly more efficient use of auto-scaling pools.

## Specifications
Some basic thoughts I had about how to do this, but they don't need to be followed.

- [ ] `helpers.add_task_to_job()` returns the task id
- [ ] Create a new function, e.g. `helpers.add_dependent_task_to_job()` that takes as an argument a collection of task ids (ideally produced by the step above). E.g. `helpers.add_dependent_task_to_job(..., depends_on: str | list[str])`
- [ ] **Alternative to above:** add an optional keyword argument to `helpers.add_task_to_job(..., dependends_on: str | list[str] | None = None)`.

**Comment by natemcintosh** [comment]
See line 60 of `NHSN/Rt/run_azure_batch/az_utils/batch.py` in [this PR](https://github.com/cdcent/cfa-nnh-pipelines/pull/233/files#diff-55c41f55ea41184eee153d5e8234f35ad5946808d4b2050dd0a4855bd77798d4) for an example.

**Comment by natemcintosh** [comment]
Also, don't forget to add the `depends_on=task_deps` part to [here](https://github.com/CDCgov/cfa_azure/blob/606962c7cb982721b15f5d4bd6495d9e91119915/cfa_azure/helpers.py#L672)
