### ISSUE TITLE
`WORKDIR` Dockerfile command does not set working directory in Azure Batch containers

### ISSUE THREAD

**Issue by arik-shurygin** [CDCgov/cfa_azure#26]
Not sure if this is directly a `cfa_azure` problem or more of a azure batch issue in general but it seems like any paths within containers have to be full absolute paths, the `WORKDIR` command in the `Dockerfile` has no impact on this. Would be nice to figure this out but is not breaking functionality right now.

**Comment by ryanraaschCDC** [comment]
I couldn't find any documenation stating how to use relative paths within the Azure Batch environment. I was previously warned by Chirag that all files would need to be absolute. I'll continue to think how we address the issue of using WORKDIR or relative paths, or at least warn the user somehow, but for now I will close this issue.
