### ISSUE TITLE
Change print statements to log statements

### ISSUE THREAD

**Issue by natemcintosh** [CDCgov/cfa_azure#4]
There comes a day in all projects when they have to move from print statements to log statements. I think this package is rapidly reaching that point.

For this package, I'd recommend following the example of the `cfa-nssp-etl` [package](https://github.com/cdcent/cfa-nssp-etl). @zsusswein has done a really great job of setting it up. 

There are a few features in particular that I think should be in this repo:
1. Creating a logger for each file, near the top of that file. See this [example](https://github.com/cdcent/cfa-nssp-etl/blob/87011d914464a25e363d39c875bdf7cf3b79c048/src/etl/load.py#L9)
2. Logging exceptions well so we have insight as to why things crash in the log files. See [example](https://github.com/cdcent/cfa-nssp-etl/blob/87011d914464a25e363d39c875bdf7cf3b79c048/src/etl/load.py#L91)
3. Setting up to log to both `stdout` and to a file. See [example](https://github.com/cdcent/cfa-nssp-etl/blob/87011d914464a25e363d39c875bdf7cf3b79c048/src/etl/pipeline.py#L87C9-L93C10)
4. Allow setting the log level from an environment variable. This one isn't quite as imperative, but can be really useful. See [example](https://github.com/cdcent/cfa-nssp-etl/blob/87011d914464a25e363d39c875bdf7cf3b79c048/src/etl/pipeline.py#L155)

**Comment by ryanraaschCDC** [comment]
@natemcintosh I've implemented the logging feature in the `new_logging` branch. If you could check it out and provide some insight, that would be extremely helpful. I'll be working on persisting the stdout and stderror separately, as noted in a different github issue
