### ISSUE TITLE
specify # of cores per node on pool creation to bring down costs

### ISSUE THREAD

**Issue by arik-shurygin** [CDCgov/cfa_azure#59]
From my understanding of our Azure architecture, we have 2 different kinds of nodes that tasks may be run on: D32S Series or A4m series. The D32S series has 32 cores, while A4m has 4 cores. They change the price of jobs significantly depending on which one is used. 

I think it would be a good idea to default to this A4m node type on calls to `client.create_pool` with an optional parameter for either 4 or 32 cores. 

In terms of how to do this I would start looking in the AzureBatchManagement class, I found a couple of promising places in the docs. Specifically in the Pool class. 
https://learn.microsoft.com/en-us/python/api/azure-mgmt-batch/azure.mgmt.batch.operations.pooloperations?view=azure-python#azure-mgmt-batch-operations-pooloperations-create

https://learn.microsoft.com/en-us/python/api/azure-mgmt-batch/azure.mgmt.batch.models.pool?view=azure-python

I think there is a spot to specify it here in your `helpers.py` specifically the `vmSize` key
https://github.com/CDCgov/cfa_azure/blob/a46345a639c35f8a169610ccb7f26317eed5efb8/cfa_azure/helpers.py#L1071-L1098

**Comment by natemcintosh** [comment]
@arik-shurygin those are just the two options we happen to be using right now, and we may not want to limit ourselves to just them. See [an introduction](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes) to the Azure VMs for an idea of the families (not even all the node types) that are available.

**Comment by arik-shurygin** [comment]
Thanks for the heads up @natemcintosh  I actually dug a little deeper and found that there is actually a parameter in our configuration tomls called `pool_vm_size` that holds the value of what node the pools should be constructed from. I agree with you that this value should not be hard-coded. 

What I am suggesting is a less expensive default node. I think for many CFAers who many just want to plug and play `cfa_azure` to run jobs on batch a 32 core machine is overkill. Obviously if they need stronger nodes they should be able to easily request them. I find default behavior to be the one most often used, so it should be cheaper unless necessary. 

I think this is just something those who hand out configuration files and keys should be aware of. I am running some more tests to see if the `pool_vm_size` parameter does what it says it does and that `cfa_azure` passes along the value correctly, I will likely close this ticket if thats the case.

**Comment by arik-shurygin** [comment]
Old Issue here but I think this can be closed now, azure cores and number can be specified via the `AzureClient.set_scaling()` command and in the config toml specifying the node type to have a certain number of cores, for example `STANDARD_D8S_v3` for 8 core machines
