### ISSUE TITLE
Allow using container images from sources other than ACR

### ISSUE THREAD

**Issue by natemcintosh** [CDCgov/cfa_azure#86]
It would be very convenient to be able to point to container images that are not necessarily stored in the Azure Container Registry. For example, the multi-signal renewal project stores has images built by Github CI, and stored in the [Github Container Registry](https://github.com/CDCgov/multisignal-epi-inference/pkgs/container/pyrenew).

I believe the only way to set the container to use is [here](https://github.com/CDCgov/cfa_azure/blob/0a245a5bec9503dc49f437caf8189db52cfa6a96/cfa_azure/clients.py#L573) or [here](https://github.com/CDCgov/cfa_azure/blob/0a245a5bec9503dc49f437caf8189db52cfa6a96/cfa_azure/clients.py#L545) which both require that the container image be in the ACR.

**Comment by xop5** [comment]
Issue has been descoped
