### ISSUE TITLE
way to disable node container_registry / storage blob caching 

### ISSUE THREAD

**Issue by arik-shurygin** [CDCgov/cfa_azure#92]
As the title suggests I would like a way to disable caching of the input/output storage blobs that are mounted onto the node for each job. This also holds for the image from the container registry as well.

In short, I often upload new versions of files to the storage blob, if I want those changes to be reflected on node I must wait for the pool to resize down to 0, then I can launch new jobs and those new nodes will have the up-to-date changes. If we can disable caching, I can save time on waiting for those nodes to wind down.

The same optimization can be applied to image uploads, those are larger and less frequent though so am ok with not implementing if the performance impact on the nodes is too great.

**Comment by ryanraaschCDC** [comment]
there's a parameter `cache_blobfuse` in the `set_pool_info`, which would solve your problem for caching the Blob storage. I'll have to see if there is a way to do something similar with the container.

**Comment by ryanraaschCDC** [comment]
There isn't a way to disable caching for the container. The closest thing to this is setting the `container` in the `add_task` method, which would pull in the container you want to use at runtime. However, there isn't a way to force an already-running node to switch containers if the container gets updated.
